### ISSUE TITLE
[feature] handle SAMP message to load an OIFITS collection

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/oiexplorer#1]
**Is your feature request related to a problem? Please describe.**
Adding the capability to receive a collection by SAMP will make interaction faster e.g. getting data from OiDB 

**Describe the solution you'd like**
OiDB could interact with OIfitsExplorer using fr.jmmc.oiexplorer.load.collection MType with a given url as argument

**Describe alternatives you've considered**
no other alternative in viex to replace classical downlad + load operations

**Additional context**
no

**Comment by gmella** [comment]
code update pushed into master

**Comment by bourgesl** [comment]
See http://jmmc.fr/~betaswmgr/OIFitsExplorer/
