### ISSUE TITLE
[bug] adding twice a file with the same filepath gives inconsistent collection state

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oiexplorer#10]
### What is the problem
If I add a file. If I add another time a file of the same filepath. Then OIFitsCollection uses the updated file content, and OIDataCollection uses the old file content. This is an inconsistent state. 

### What did you expect
Both collections to be updated. Every reference to the old OIFitsFile object must disappear.

### Describe how to reproduce or add a test
- have a file named "~/input.fits" -or whatever other path-
- open OIExplorer
- add the file
- eventually replace "~/input.fits" on your disk by some different fits content (keep the same filepath)
- add the file again
  - you are in an inconsistent state
  - if you changed the content, you can look at data tree panel and try to select, it still display the old file content
  - maybe there are other things broken I did not test everything

### Context information
- Java version 1.8
- Operating system Linux Mint
- 64 bit
- How is the application installed? Netbeans master github branch

### Technical details
The culprit is the function `OIFitsCollectionManager.addOIFitsFile`. It calls `OIFitsCollection.addOIFitsFile` which replaces the old OIFitsFile object by the new one, and then it does *not* do the same for `OIDataCollection`, whereas it should. BTW there is a related TODO in OIFItsCollection.addOIFitsFile

**Comment by buthanoid** [comment]
### technical problem

- the `OIFitsCollectionManager` (OCM) class contains two collection classes: `OIFitsCollection` & `OiDataCollection`
- OCM has a method to add an OIFitsFile: `addOIFitsFile(OIFitsFile)`. 
  - it calls the add method of `OIFitsCollection`:  `addOIFitsFile(OIFitsFile)`
    - this add the OIFitsFile. If there were a previous OIFitsFile with the same filepath, it begins by removing this previous file from the collection
  - then, only if there was no previous file in OIFitsCollection, it adds an OIDataFile to OiDataCollection. Thus it is inconsistent: updating OIFitsCollection and not OiDataCollection. 

### solution 1

- Never add an OIFitsFile when there is already one with the same filepath in the collection
  - modify `OIFitsCollection.addOIFitsFile` to do nothing when there is a previous file 

### solution 2

- Modify both collections
  - modify `OIFitsCollectionManager.addOIFitsFile` to modify the current OIDataFile if there exist one... that is, replace the reference to the old OIFitsFile by the new one. in this way, no need to modify the TableUID as they would still point to the same OIDataFile object.

**Comment by bourgesl** [comment]
I think this bug is related to missing reference checks... I am implementing now.

Anyway I agree solution 2 is expected: explicit update any or first oidatafile reference ( as filepath is unique) is better
