### ISSUE TITLE
[feature] Basic filter implementation

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/oiexplorer#11]
**Is your feature request related to a problem? Please describe.**
Yes , I need to be able to filter my data as done in the command line interface.

**Describe the solution you'd like**
I would like to be able to define a filter list in the GUI starting with a list of wavelength ranges. Exported data and plotted ones should correspond to the ones which would have been merged with the same wavelengh ranges using the OIFitsProcess in command line.

**Additional context**
Further filters (date, baselines...) will be added in the following iterations.

** Technical constraints **
The implementation must evaluate the reuse of the merger bitmask by the plotChartPanel code. 'Export to OIfits file' action should use in addition to the currently selected target the new filter inputs.

**Comment by buthanoid** [comment]
Draft proposal:
- create a new class `GenericFilter extends Identifiable(String columnName, type=string/numeric, acceptedValues=List<String or Range>, enabled=true/false)`
- add a `List<GenericFilter>` field to `SubsetDefinition`
- add a `SelectorResult` field to `SubsetDefinition`, replace the former fake OIFitsFile reference, fix all usages
- add a `Map<OIWavelength, IndexMask> wavelengthMasks` field to `SelectorResult`
- add a new GUI widget to edit 1 wavelength range for now: wave min & wave max. pre-filled with initial values (no), see `AxisEditor` (later support for multiple ranges)
- modifying the widget modifies `SubsetDefinition.List<GenericFilter>`, that will call `updateSubsetDefinition` to query data
- `updateSubsetDefinitionRef` will use `OCM.findOIData(subsetDefinition)` to get a `SelectorResult`, update `SubsetDefinition.SelectorResult` field with the newly computed `SelectorResult`
- OCM.findOIData(subsetDefinition) will define the wavelength criteria from the `SubsetDefinition` on the `Selector` instance and delegate to `oiFitsCollection.findOIData(selector, result)`
- `OIFitsCollection.findOIData(selector, result)` will compute `SelectorResult.wavelengthMasks` while computing the `SelectorResult`. It will use a code similar to `Merger.processOIWavelengths`. It does it for every `OIWavelength` used by matching `OIData` tables. If all table is hidden, no mask is added. If all table is valid, a null value is added as mask. SelectorResult stores the masks through the successive calls to `findOIData(Selector,SelectorResult)`
- `PlotChartPanel.updatePlot()`, for each `OIData`, gets the related `OIWavelength`, then the `IndexMask` from `SubsetDefintion.SelectorResult.wavelengthMasks`. It gives it to the `updatePlot(parameters)` function, which uses the `IndexMask` to skip the unwanted values when it iterates on the waves channels. Also handle the cases when there is no masks and when mask is null.

Notes:
- wavelength masks are using `BitSet` (1D) along the wavelength axis used like `OIVIS2[row index][wlen index]`.
- a bit set to false means "hide".
- row masks are using BitSet (1D) along the table axis like `TARGET_ID[row index]`.
- 2D masks will be later necessary to mimic the `FLAGS` column for more complex filter expressions like `VIS2ERR[row][wlen] < threshold_value`
- currently IndexMask handle the three cases. to be refined when needed

**Comment by buthanoid** [comment]
About the replacement of Subset OIFitsFile by the SelectorResult, in SubsetDefinition. The following points remain to be treated:
- PlotCharPanel, function getOiFitsSubset
- PlotDefinitionEditor, function onProcess
- PlotView, function updateDataView

**Comment by bourgesl** [comment]
I fixed all former subsetDefinition.OIFitsFile usages except OIFitsBrowser ...
Merger has been updated to use SelectorResult's IndexMask
