### ISSUE TITLE
Add a button to invert filter logic 

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/oiexplorer#23]
Getting a toggle button that invert the filter logic would be very nice to get the data complement in a smart way.

Of course this should be translated to the CLI using a simple syntax:
may be something like:
-eff_wave _4.2999999999999995E-6,4.8E-6 
or 
-eff_wave not4.2999999999999995E-6,4.8E-6 
or a more sophisticated way using positional operators:
-not -eff_wave 4.2999999999999995E-6,4.8E-6 

Youpee in advance,

**Comment by bourgesl** [comment]
The checkbox [ ] X (as exclude) added. The prefix in CLI args is 'not:' like "-eff_wave not:4.3E-6,4.8E-6 "
