### ISSUE TITLE
Plot dataset coming from individual monochromatic OIFits with colors

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/oiexplorer#30]
**Is your feature request related to a problem? Please describe.**
I would like to look at wavelength distribution plotting data from a collection of monochromatic OIFIts. At present time all measurement points are shown in black.

**Describe the solution you'd like**
I would like to get the last new cool colormap to plot all data even if they come from monochromatic individual data files

**Additional context**
Here comes a good test collection :
https://oidb.jmmc.fr/search.html?collection=~J%2FA%2BA%2F593%2FA45

**Comment by bourgesl** [comment]
Fixed cases:
- many 1 channel files (vega)
- mixed 1 channel file (pionier or iota) with other instruments

**Comment by gmella** [comment]
I checked your new code which provides beautiful colors :)
Thx !
