### ISSUE TITLE
Set aspect ratio of UV plots to 1

### ISSUE THREAD

**Issue by jean-philippeberger** [JMMC-OpenDev/oiexplorer#31]
The uvplots provided by OiFitsExplorer should have the same scaling on the u and v dimensions (aspect ratio set to one).

**Comment by gmella** [comment]
The orientation of U may be also be discussed and other associated items pointed in #32

**Comment by gmella** [comment]
Aspro2, OiFitsExplorer and OImaging beta releases now have squared UV plots.
