### ISSUE TITLE
[bug] Deleting view breaks data selection

### ISSUE THREAD

**Issue by buthanoid** [JMMC-OpenDev/oiexplorer#9]
### What is the problem
After deleting a view, Selection does nothing. my left view does not change, the plot displays data unrelated to my selection.

### What did you expect
Selection to change my data, like the normal usage

### Describe how to reproduce or add a test
- Start OIExplorer
- Add a File
- In the Data Tree Panel, expand to tables, and select one table
- In the View Panel, click on "+" to add a view (you will then be switched to view 1)
- In the View panel, click on "x" on view 1 (you will then be switched to view 0)
- try to modify selection in the Data Tree Panel, you will see that the plot is not updated

### Context information
Please always add the following information
- Java version 1.8
- Operating system Linux Mint
- 64 bit
- How is the application installed? built and ran from master branch with netbeans
- Any custom changes: no

**Comment by bourgesl** [comment]
I reproduced the problem: subset is null ...
I will fix the remove code to ensure object are orphans.
